### ISSUE TITLE
Feature Roadmap - 1.0

### ISSUE THREAD

**Issue by christophery** [christophery/proton#2]
These features are pending and can be subject to change:

- [x] Dark Mode
- [x] Infinite Scrolling
- [x] Customizer
- [x] Related posts footer
- [x] Search
- [x] Social icons

### Customizer Settings

- [x] Brand - Accent color
- [x] Brand- Social Icons
- [x] Sitewide - Color scheme (light, dark, auto)
